### ISSUE TITLE
Should this repo be handed over to the OTP team

### ISSUE THREAD

**Issue by ypaq** [c0b/docker-erlang-otp#38]
Wondering if this repo should be maintained by the OTP team.

**Comment by c0b** [comment]
sure, if the OTP team want,

the thing is since 2 years ago I started this project, I did send email asking on the mailing list, at that moment there seemingly wasn't enough interest; you may invite that team members discuss here if that situation has changed in the past 2 years;

**Comment by tsloughter** [comment]
I think there may be interest now.

**Comment by c0b** [comment]
> I think there may be interest now.

may be or for sure there are multiple ones have interest to take maintenance? it's always a better thing to have a team to share maintaining the project (better than me alone), this one started for better visibility by taking the DockerHub entry http://hub.docker.com/_/erlang/ and I hope a team can help make faster cycle for each Erlang release to be available thru DockerHub, and some potential feature development;
Some of you may be aware that OpenX (https://github.com/openx) sponsor'ed part of my time to turn this project to reality, just because OpenX uses Erlang a lot; in office I just chatted with Anthony he had longer time in the Erlang community and knows many of you offline as well, so I would say no problem, feel proud for this project can be part of the bigger Erlang family
For more details of transition plan I just wonder how would it be implemented? is it like a repo under https://github.com/erlang org? I would like that https://github.com/erlang/docker-erlang-otp, just make proper permission for me to be able continue contribute some effort

Things on my TODO list (as well as the regular release bump):
1. Make the Alpine image, hopefully can be done when Erlang20 is out!
   I understand in the Erlang community there are multiple ways to deploy code to production, even long time before Docker was born, while undoubtedly Docker way of software deployment is increasingly popular, many other programming language communities have the alpine based docker image already, there's no reason Erlang shouldn't; It's all about choices, to make a slimmer image than current `erlang:slim` (~280MB), an alpine based full featured Erlang image can very likely be done under 50MB; hopefully to see soon

**Comment by c0b** [comment]
anyone has progress communicating this with the OTP team?

**Comment by tsloughter** [comment]
I talked to Kenneth and he supports getting this under the erlang org.

**Comment by c0b** [comment]
@tsloughter wonder how would we make progress of this?
my thinking was if some of you can make a repo under https://github.com/erlang 
 (naming it like https://github.com/c0b/docker-erlang-otp) and grant me proper contributor permission, I would be happy to continue maintaining there ; also I would like to nominate / support some active contributors to have contributor permission there as well, especially the @getong has demonstrated ability and skills since April of last year and kept very active in the past 12 months :+1:
    https://github.com/c0b/docker-erlang-otp/graphs/contributors

**Comment by tsloughter** [comment]
I'll try getting this moving again.

Maybe @garazdawi can poke someone :).

**Comment by garazdawi** [comment]
I'll try to get things moving.

**Comment by garazdawi** [comment]
So, in order to transfer this repository, so that tickets and other non-git history remains, we need to add @c0b to the http://github.com/erlang organization, and also temporarily grant members the permission to create repositories. At that point @c0b should be able to transfer this project.

I'll start putting things in motion once I get an ack that this is ok with @c0b.

**Comment by c0b** [comment]
Sure, I feel good with that @garazdawi

**Comment by proxyles** [comment]
@c0b you should have an invitation pending.

I Think everything should be doable from your end now.
if not, email me and we will figure it out henrik @ erlang

**Comment by c0b** [comment]
@proxyles thanks for that, I can see myself in this team now
https://github.com/orgs/erlang/teams/docker-erlang-otp/members  but still do not have permission to create a new repo over there, maybe you can just use fork button this repo to the erlang org then add me as collaborator into the forked repo, that should be sufficient permission

Another thing I can see we may need to clarify is since there's already a `docker-erlang` repo and if I create a new `docker-erlang-otp` repo there, that may get some people confused, do you have more visibility why is it there, it looks like a good sample Dockerfile with a sample Erlang app, 
https://github.com/erlang/docker-erlang
https://github.com/erlang/docker-erlang/blob/master/Docker-Cheat-Sheet.md  this file mentioned `for future googlers` is this a repo from a Google employee's internal project?
https://github.com/erlang/docker-erlang/graphs/contributors 
![image](https://user-images.githubusercontent.com/14798161/39319305-8cd03226-4935-11e8-9587-d4546dbf0872.png)

**Comment by proxyles** [comment]
That repo is an example done by Björn-Egil and Lukas I think it was.
I will check tomorrow if we should keep it or not, you now have permission on our github.
With great power comes great responsibility 🤤 
Create what you need, and You will be in a team resp for that repo!

**Comment by tsloughter** [comment]
I think we should keep it but it needs updating. I've been meaning to send a PR.

But maybe rename it to `docker-erlang-example`.

**Comment by proxyles** [comment]
yes, that or move it into this one as an example

**Comment by c0b** [comment]
I see; so now https://github.com/erlang/docker-erlang-otp is there live!

> With great power comes great responsibility 🤤 

Yes! while maybe you @proxyles were dropping my permission during my operation, the actual window is very short which is fine,   I do not need permission to other repos under erlang org;  but I'd like to have maintainer permission in this team to this `docker-erlang-otp` repo ; I have done some cleaning of too old stale branches, would like to do some more cleaning work there in the following a few days and take the longer term maintenance

https://github.com/orgs/erlang/teams/docker-erlang-otp/members

The other thing is this new repo disabled issues board? Usually I'd like to keep the github issues board,  because otherwise where would you expect people to report issues? Is everything goes to erlang-questions@ (may overload it?) or another mailing-list?
the github issues still has the flexibility of only subscribing a few interested issues only, and it's automatic subscribed if anyone commented on an issue, I would usually avoid subscribe some ML if its volume is too high

http://erlang.org/pipermail/erlang-questions/2018-April/thread.html
http://erlang.org/mailman/listinfo

**Comment by proxyles** [comment]
@c0b You should have maintainer on the repos associated with the group.
I double checked .
I think if you had used the:
"Transfer ownership
Transfer this repository to another user or to an organization where you have the ability to create repositories. "

Instead of a clone, all the current issues and PRs etc would have been transferred as well.

If you like, we can arrange for that tomorrow, now im off to bed!
We can continue this on email?
henrik@erlang.org

**Comment by c0b** [comment]
Sure. I close this issue and continue with email.
