### ISSUE TITLE
Alpine by default?

### ISSUE THREAD

**Issue by tsloughter** [c0b/docker-erlang-otp#52]
I was curious if the images would be moving to alpine by default or sticking with debian. My understanding was that docker wanted the official images to be alpine based. Is this the case?

**Comment by c0b** [comment]
here may be following other language docker images' convention: default image is `buildpack-deps` based which is debian + gcc compiler suite + download tools + scm tools; an alpine image is separately provided for production deployment

1. https://hub.docker.com/_/golang/
2. https://hub.docker.com/_/python/
3. https://hub.docker.com/_/node/
4. https://hub.docker.com/_/ruby/
5 ...

however on this topic I am open if more people want alpine to be the default, will need a good reason for https://github.com/docker-library repos to break the convention

**Comment by getong** [comment]
Besides, debian stretch is released, and the docker official image has updated it. May I update it and make a PR? @c0b

**Comment by c0b** [comment]
i see, by checking above 4 other language images, I am seeing only `golang:1.9beta1` is based from `buildpack-deps:stretch-scm` at this point, others are still on `buildpack-deps:jessie` we may be better to stay with it for longer time? we'd better to be conservative on the underlying OS version
because as I think, most of this erlang image users will care more about Erlang version than OS variants, right

if someone says why not just add another variant? think about `number of Erlang versions` \* `number of OS variants, versions` that combination will be too many;
I want to count golang image here as a negative example, because it's provided with stretch, wheezy, and default uses jessie, alpine3.5 alpine3.6 is just too many combinations, kind of distracting; to most users if their app can be running well, who would care the underlying OS? if the docker hub entry page for an image (https://hub.docker.com/_/golang/ or https://hub.docker.com/_/erlang/) have too many choices, would that be confusing

as a response to the other PR #51 `for older versions (i.e. 17 and backwards).` I would actually like to deprecate the 17 and older ones, depends on what popularity the 17 still has, may give it another half year? then can eliminate 17 from the docker hub page.

**Comment by tsloughter** [comment]
I'm fine either way. I asked because I thought it might be the way things were going and wanted to be prepared :)

**Comment by tsloughter** [comment]
And yea, the exact OS version shouldn't matter that much. Particularly since these images should be used for building and not running a system. Meaning the issue is OS lib compatibility, you can then use the build artifact (like a release including erts) in any compatible image. Would be even less of an issue if alpine didn't use musl :).

**Comment by tsloughter** [comment]
I can close this one. But I just went to give alpine a try and discovered the erlang alpine images don't come with rebar3, why is that?

**Comment by c0b** [comment]
I see most people use alpine images for production deployment, the minimum image size would be preferred over feature rich? the slim image doesn't have rebar/rebar3 either

https://github.com/c0b/docker-erlang-otp/blob/master/20/alpine/Dockerfile

**Comment by tsloughter** [comment]
They should be used for building the image, not running your code in production. The same as a Go alpine image should have the Go compiler and libraries and then you build a raw alpine image with the binary you built. With Erlang you build a release and run that on a raw alpine image.

I don't see the use of having an Erlang image without dev tools or most libraries.
